# Generated by Django 4.0.4 on 2022-05-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_finish_at_alter_player_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='finish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Matthew', max_length=32),
        ),
    ]
